uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents/relreases/latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  tx_delay: 10ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_length: 8
  rx_checksum: add
  tx_checksum: add

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False


#일괄소등
#상태      Head,   ON,   ID, 0x00, 0x00, 0x00, 0x00, add checksum 
#상태 ON   0xA0, 0x01, 0x01, 0x00, 0x00, 0x17, 0x00, add checksum
#상태 OFF  0xA0, 0x00, 0x01, 0x00, 0x00, 0x17, 0x00, add checksum
#응답 ON   0xA2, 0x01, 0x01, 0x00, 0x00, 0x17, 0x00, add checksum
#응답 OFF  0xA2, 0x00, 0x01, 0x00, 0x00, 0x17, 0x00, add checksum

#명령      Head,   ID,   On, 0x00, 0x00, 0x00, 0x00, add checksum 
#명령 ON   0x22, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, add checksum
#명령 OFF  0x22, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, add checksum


#조명
#상태      Head,   ON,   ID, 0x00, 0x00, 0x00, 0x00, add checksum 
#상태 ON   0xB0, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#상태 OFF  0xB0, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#응답 ON   0xB1, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#응답 OFF  0xB1, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum

#명령      Head,   ID,   On, 0x00, 0x00, 0x00, 0x00, add checksum 
#명령 ON   0x31, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#명령 OFF  0x31, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, add checksum
light:
  - platform: uartex
    name: "Light Breaker"
    state: 
      data: [0xA0, 0x00, 0x01]
      mask: [0xF0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x22, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00]
      ack: [0xA2, 0x01, 0x01]
    command_off:
      data: [0x22, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00]
      ack: [0xA2, 0x00, 0x01]

  - platform: uartex
    name: "Light 1"
    state: 
      data: [0xB0, 0x00, 0x01]
      mask: [0xF0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x31, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x01, 0x01]
    command_off:
      data: [0x31, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x00, 0x01]

  - platform: uartex
    name: "Light 2"
    state: 
      data: [0xB0, 0x00, 0x02]
      mask: [0xF0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x31, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x01, 0x02]
    command_off:
      data: [0x31, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x00, 0x02]

  - platform: uartex
    name: "Light 3"
    state: 
      data: [0xB0, 0x00, 0x03]
      mask: [0xF0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x31, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x01, 0x03]
    command_off:
      data: [0x31, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x00, 0x03]

  - platform: uartex
    name: "Light 4"
    state: 
      data: [0xB0, 0x00, 0x04]
      mask: [0xF0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x31, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x01, 0x04]
    command_off:
      data: [0x31, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x00, 0x04]


#상태      Head,   ON,   ID,  Cur,  Tar, 0x00, 0x00, add checksum 
#상태 ON   0x82, 0x81, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum
#상태 OFF  0x82, 0x80, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum
#상태 HEAT 0x82, 0x83, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum
#응답 ON   0x84, 0x81, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum
#응답 OFF  0x84, 0x80, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum
#응답 HEAT 0x84, 0x83, 0x01, 0xXX, 0xXX, 0x00, 0x00, add checksum

#명령        Head,   ID,  CMD,   ON, 0x00, 0x00, 0x00, add checksum 
#명령 ON     0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00, add checksum
#명령 OFF    0x04, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00, add checksum
#명령 OFF    0x04, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00, add checksum
#명령 CHANGE 0x04, 0x01, 0x03, 0xXX, 0x00, 0x00, 0x00, add checksum
climate:
  - platform: uartex
    name: "Heater 1"
    visual:
      min_temperature: 5 °C
      max_temperature: 40 °C
      temperature_step: 1 °C
    state: 
      data: [0x80, 0x00, 0x01]
      mask: [0xF9, 0x00, 0xFF]
    state_temperature_current: 
      offset: 3
      signed: False
      bcd: True
    state_temperature_target:
      offset: 4
      signed: False
      bcd: True
    state_off:
      offset: 1
      data: [0x80]
    state_heat:
      offset: 1
      data: [0x00]
      mask: [0x0F]
      inverted: True
    command_off:
      data: [0x04, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x01]
    command_heat:
      data: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x01]
    command_temperature: !lambda |-
      uint8_t target = float_to_bcd(x);
      return {{0x04, 0x01, 0x03, (uint8_t)target, 0x00, 0x00, 0x00},{0x84, 0x00, 0x01},{0xFF, 0x00, 0xFF}};

  - platform: uartex
    name: "Heater 2"
    visual:
      min_temperature: 5 °C
      max_temperature: 40 °C
      temperature_step: 1 °C
    state: 
      data: [0x80, 0x00, 0x02]
      mask: [0xF9, 0x00, 0xFF]
    state_temperature_current: 
      offset: 3
      signed: False
      bcd: True
    state_temperature_target:
      offset: 4
      signed: False
      bcd: True
    state_off:
      offset: 1
      data: [0x80]
    state_heat:
      offset: 1
      data: [0x00]
      mask: [0x0F]
      inverted: True
    command_off:
      data: [0x04, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x02]
    command_heat:
      data: [0x04, 0x02, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x02]
    command_temperature: !lambda |-
      uint8_t target = float_to_bcd(x);
      return {{0x04, 0x02, 0x03, (uint8_t)target, 0x00, 0x00, 0x00},{0x84, 0x00, 0x02},{0xFF, 0x00, 0xFF}};

  - platform: uartex
    name: "Heater 3"
    visual:
      min_temperature: 5 °C
      max_temperature: 40 °C
      temperature_step: 1 °C
    state: 
      data: [0x80, 0x00, 0x03]
      mask: [0xF9, 0x00, 0xFF]
    state_temperature_current: 
      offset: 3
      signed: False
      bcd: True
    state_temperature_target:
      offset: 4
      signed: False
      bcd: True
    state_off:
      offset: 1
      data: [0x80]
    state_heat:
      offset: 1
      data: [0x00]
      mask: [0x0F]
      inverted: True
    command_off:
      data: [0x04, 0x03, 0x04, 0x00, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x03]
    command_heat:
      data: [0x04, 0x03, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x03]
    command_temperature: !lambda |-
      uint8_t target = float_to_bcd(x);
      return {{0x04, 0x03, 0x03, (uint8_t)target, 0x00, 0x00, 0x00},{0x84, 0x00, 0x03},{0xFF, 0x00, 0xFF}};

  - platform: uartex
    name: "Heater 4"
    visual:
      min_temperature: 5 °C
      max_temperature: 40 °C
      temperature_step: 1 °C
    state: 
      data: [0x80, 0x00, 0x04]
      mask: [0xF9, 0x00, 0xFF]
    state_temperature_current: 
      offset: 3
      signed: False
      bcd: True
    state_temperature_target:
      offset: 4
      signed: False
      bcd: True
    state_off:
      offset: 1
      data: [0x80]
    state_heat:
      offset: 1
      data: [0x00]
      mask: [0x0F]
      inverted: True
    command_off:
      data: [0x04, 0x04, 0x04, 0x00, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x04]
    command_heat:
      data: [0x04, 0x04, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x04]
    command_temperature: !lambda |-
      uint8_t target = float_to_bcd(x);
      return {{0x04, 0x04, 0x03, (uint8_t)target, 0x00, 0x00, 0x00},{0x84, 0x00, 0x04},{0xFF, 0x00, 0xFF}};


#상태      Head,   ON,   ID,  SPD, 0x00, 0x00, 0x00, add checksum 
#상태 OFF  0xF6, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#상태 LOW  0xF6, 0x04, 0x01, 0x01, 0x00, 0x00, 0x00, add checksum
#상태 MID  0xF6, 0x04, 0x01, 0x02, 0x00, 0x00, 0x00, add checksum
#상태 HIGH 0xF6, 0x04, 0x01, 0x03, 0x00, 0x00, 0x00, add checksum
#상태 AUTO 0xF6, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, add checksum
#상태 NIGH 0xF6, 0x06, 0x01, 0x01, 0x00, 0x00, 0x00, add checksum

#응답 OFF  0xF8, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum
#응답 LOW  0xF8, 0x04, 0x01, 0x01, 0x00, 0x00, 0x00, add checksum
#응답 MID  0xF8, 0x04, 0x01, 0x02, 0x00, 0x00, 0x00, add checksum
#응답 HIGH 0xF8, 0x04, 0x01, 0x03, 0x00, 0x00, 0x00, add checksum

#명령      Head,   ID,  CMD,  SPD, 0x00, 0x00, 0x00, add checksum 
#명령 OFF  0x78, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, add checksum 
#명령 ON   0x78, 0x01, 0x01, 0x04, 0x00, 0x00, 0x00, add checksum 
#명령 LOW  0x78, 0x01, 0x02, 0x01, 0x00, 0x00, 0x00, add checksum 
#명령 MID  0x78, 0x01, 0x02, 0x02, 0x00, 0x00, 0x00, add checksum 
#명령 HIGH 0x78, 0x01, 0x02, 0x03, 0x00, 0x00, 0x00, add checksum 
fan:
  - platform: uartex
    name: "Fan 1"
    state:
      data: [0xF0]
      mask: [0xF1]
    state_on:
      offset: 1
      data: [0x00]
      inverted: True
    state_off:
      offset: 1
      data: [0x00]
    command_on:
      data: [0x78, 0x01, 0x01, 0x04, 0x00, 0x00, 0x00]
      ack: [0xF8, 0x04]
    command_off:
      data: [0x78, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xF8, 0x00]
    command_speed: !lambda |-
      uint8_t speed = x;
      return {{0x78, 0x01, 0x02, speed, 0x00, 0x00, 0x00},{0xF8, 0x04}};
    state_speed: !lambda |-
      return data[3];
    preset_modes:
      - "Auto"
      - "Night"
    state_preset: !lambda |-
      if (data[1] == 0x02) return "Auto";
      if (data[1] == 0x06) return "Night";
      return "";

#상태      Head,   ON,   ID, 0x00, 0x00, 0x00, 0x00, add checksum 
#상태 ON   0x90, 0x80, 0x80, 0x00, 0x00, 0x00, 0x00, add checksum
#상태 OFF  0x90, 0x40, 0x40, 0x00, 0x00, 0x00, 0x00, add checksum
#응답 OFF  0x91, 0x88, 0x88, 0x00, 0x00, 0x00, 0x00, add checksum

#명령      Head,   ID,   On, 0x00, 0x00, 0x00, 0x00, add checksum 
#명령 OFF  0x11, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00, add checksum
valve:
  - platform: uartex
    name: "Gas Valve"
    state: 
      data: [0x90]
    state_open:
      offset: 1
      data: [0x80, 0x80]
    state_closed:
      offset: 1
      data: [0x40, 0x40]
    command_close:
      data: [0x11, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00]
      ack: [0x91, 0x88, 0x88]


#상태 ELV 0x23, 0x01, 0xXX, 0x00, 0x00, 0x00, 0x00, add checksum
sensor:
  - platform: uartex
    name: "Elevator Floors"
    icon: "mdi:elevator"
    state: 
      data: [0x23]
    state_number:
      offset: 2
      length: 1
      precision: 0

#명령 0xA0, 0x01, 0x01, 0x00, 0x08, 0x15, 0x00, add checksum 
button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0xA0, 0x01, 0x01, 0x00, 0x08, 0x15, 0x00]
      ack: [0x23]
