uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents@latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3
  rx_header: [0xF7]
  tx_header: [0xF7]
  rx_footer: [0xAA]
  tx_footer: [0xAA]
  rx_checksum: add_no_header
  tx_checksum: add_no_header

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

#작성중
light:
  - platform: uartex
    name: "Room 0 Light 1"
    state: 
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x11, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 2"
    state: 
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 5
      data: [0x01]
    state_off:
      offset: 5
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x12, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 3"
    state: 
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 6
      data: [0x01]
    state_off:
      offset: 6
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x13, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 1 Light 1"
    state: 
      data: [0x20, 0x01, 0x22]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on: 
      data: [0x20, 0x22, 0x01, 0x11, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x22, 0x9F]
    command_off:
      data: [0x20, 0x22, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x22, 0x9F]

fan:
  - platform: uartex
    name: "Fan 1"
    state:
      data: [0x20, 0x01, 0x71]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on:
      data: [0x20, 0x71, 0x01, 0x11, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x71, 0x91]
    command_off:
      data: [0x20, 0x71, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x71, 0x91]
    command_speed: !lambda |-
      uint8_t speed = x;
      return {{0x20, 0x71, 0x01, 0x11, 0x01, 0x01, speed, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x71, 0x91}};
    state_speed:
      offset: 6
      signed: False

valve:
  - platform: uartex
    name: "Gas Valve"
    device_class: gas
    state:
      data: [0x20, 0x01, 0x11]
    state_closed:
      offset: 4
      data: [0x00]
    state_open:
      offset: 4
      data: [0x01]
    command_close:
      data: [0x20, 0x11, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x11, 0x91]

climate:
  - platform: uartex
    name: "Heater 1"
    id: "heater_1"
    visual:
      min_temperature: 6 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current: 
      offset: 5
    state_temperature_target: !lambda |-
      return ((uint8_t)data[4] & 0x7F);
    state_off:
      offset: 4
      data: [0x00]
      mask: [0x80]
    state_heat:
      offset: 4
      data: [0x80]
      mask: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_1).target_temperature;
      return {{0x20, 0x41, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x41, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_1).target_temperature + 0x80;
      return {{0x20, 0x41, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x41, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x + 0x80;
      return {{0x20, 0x41, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x41, 0x91}};

  - platform: uartex
    name: "Heater 2"
    id: "heater_2"
    visual:
      min_temperature: 6 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current: 
      offset: 7
    state_temperature_target: !lambda |-
      return ((uint8_t)data[6] & 0x7F);
    state_off:
      offset: 6
      data: [0x00]
      mask: [0x80]
    state_heat:
      offset: 6
      data: [0x80]
      mask: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_2).target_temperature;
      return {{0x20, 0x42, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x42, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_2).target_temperature + 0x80;
      return {{0x20, 0x42, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x42, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x + 0x80;
      return {{0x20, 0x42, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x42, 0x91}};

  - platform: uartex
    name: "Heater 3"
    id: "heater_3"
    visual:
      min_temperature: 6 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current: 
      offset: 9
    state_temperature_target: !lambda |-
      return ((uint8_t)data[8] & 0x7F);
    state_off:
      offset: 8
      data: [0x00]
      mask: [0x80]
    state_heat:
      offset: 8
      data: [0x80]
      mask: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_3).target_temperature;
      return {{0x20, 0x43, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x43, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_3).target_temperature + 0x80;
      return {{0x20, 0x43, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x43, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x + 0x80;;
      return {{0x20, 0x43, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x43, 0x91}};

  - platform: uartex
    name: "Heater 4"
    id: "heater_4"
    visual:
      min_temperature: 6 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current: 
      offset: 11
    state_temperature_target: !lambda |-
      return ((uint8_t)data[10] & 0x7F);
    state_off:
      offset: 10
      data: [0x00]
      mask: [0x80]
    state_heat:
      offset: 10
      data: [0x80]
      mask: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_3).target_temperature;
      return {{0x20, 0x44, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x44, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_3).target_temperature + 0x80;
      return {{0x20, 0x44, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x44, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x + 0x80;
      return {{0x20, 0x44, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x44, 0x91}};

sensor:
  - platform: uartex
    name: "Elevator Floors"
    icon: "mdi:elevator"
    state: 
      data: [0x20, 0x01, 0x22, 0x81]
    state_number:
      offset: 4

# 0x20, 0x01, 0xE1, 0x81, 0x02, 0x00, 0x00, 0x00, 0x00, 0x02, 0x31, 0x30
# 0x20, 0x01, 0xE1, 0x81, 0x02, 0x00, 0x01, 0x00, 0x00, 0x02, 0x31, 0x33
# 0x20, 0x01, 0xE1, 0x81, 0x02, 0x00, 0x01, 0x00, 0x00, 0x04, 0x30, 0x38
button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x20, 0x01, 0xE1, 0x81, 0x02, 0x00, 0x00, 0x00, 0x00, 0x02, 0x31, 0x30]