name: Update latest Release

on:
  release:
    types:
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Update or Create latest Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const latestTag = 'latest';
            let currentRelease;
            console.log("Fetching the latest release using the API");
            try {
              const latestResponse = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              currentRelease = latestResponse.data;
            } catch (error) {
              throw new Error("No published release found to update latest");
            }
            console.log("Current Release:", currentRelease);

            // 릴리즈의 target_commitish 대신 실제 릴리즈 태그의 commit SHA를 가져옵니다.
            const releaseTagName = currentRelease.tag_name;
            console.log(`Fetching commit SHA for release tag: ${releaseTagName}`);
            const tagRef = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${releaseTagName}`,
            });
            const currentSha = tagRef.data.object.sha;
            console.log(`Found commit SHA for latest release: ${currentSha}`);

            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${latestTag}`,
                sha: currentSha,
                force: true,
              });
              console.log('Updated tag latest');
            } catch (error) {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${latestTag}`,
                sha: currentSha,
              });
              console.log('Created tag latest');
            }
